### ISSUE TITLE
question about raft visualization

### ISSUE THREAD

**Issue by haima-zju** [raft/raft.github.io#100]
S2 is voted as leader，but its last log never commit。
In the 5th term, S5 is leader. A new request comes from client, S5 do its leader job and commit this entry finally, but this commit request from S5 does not reach S2. At the time, S3 start a new leader election because of time out, but S3 fail to be leader, and the group enter to term 6.  After a litter time, S5 time out, and start a new leader with term 7, the propose request contain last log info, whose index is the uncommitted log index. Is that right? finally, S5 become leader

**Comment by haima-zju** [comment]
![Uploading 屏幕快照 2019-04-17 下午2.39.52.png…]()
this is screenshot

**Comment by haima-zju** [comment]
<img width="832" alt="screenshot" src="https://user-images.githubusercontent.com/5483225/56267993-ee853380-6122-11e9-9f58-7887f32e7d22.png">

**Comment by ongardie** [comment]
Please ask Raft questions on https://groups.google.com/forum/#!forum/raft-dev
