### ISSUE TITLE
New Python implementation

### ISSUE THREAD

**Issue by Oaklight** [raft/raft.github.io#107]
Hi!

My friend [Nicola](https://github.com/nmanzini) and I just published our Python implementation.
Pls, add our [Vesper](https://github.com/Oaklight/Vesper) project to the website list.

Best,
Peng

**Comment by ongardie** [comment]
Cool. Do you mind submitting a PR?

Thanks,
Diego

**Comment by Oaklight** [comment]
What's a PR? Could you be more specific?

**Comment by Oaklight** [comment]
Hi Diego,

PR is filed. Pls take a look.

Cheers,
Peng

**Comment by ongardie** [comment]
merged in #108
