### ISSUE TITLE
Error in Figure 2 description?

### ISSUE THREAD

**Issue by rnewson** [raft/raft.github.io#172]
The description for figure 2 in https://raft.github.io/raft.pdf reads;

"A condensed summary of the Raft consensus algorithm (excluding membership changes and log compaction). The server
behavior in the upper-left box is described as a set of rules that trigger independently and repeatedly."

The second sentence confused me momentarily. I believe it should refer to the "lower-right box" as it does in the original dissertation PDF.

**Comment by ongardie** [comment]
You're right. It's a known error. So far, my list of errata for the paper doesn't justify putting out a new revision, which could result in its own confusion. (And of course, the published version can't be updated.)

BTW, this repo is intended for the website. For discussions about the paper, please use the raft-dev mailing list.
