### ISSUE TITLE
Raft implementation in Omnet++

### ISSUE THREAD

**Issue by EdoardoV97** [raft/raft.github.io#176]
In the past months me and a colleague [Leonardo Ruzza](https://github.com/LeonardoRuzza) have worked on an implementation of Raft in [Omnet++](https://omnetpp.org/). 

Our main goal was to provide a handy tool to simulate the protocol in action without the need to build a real distributed environment. We think this can be very useful both to understand the protocol functioning and to have a first preview of how a real network of machines using the protocol would behave.  
Our repo is private at the moment, but I would like to ask If it can be of use for someone and so made it public; also, it would be an honor to be added to the implementation list.

Edoardo Venir
Leonardo Ruzza

**Comment by ongardie** [comment]
Hi @EdoardoV97 and @LeonardoRuzza,

I'm not familiar with Omnet++, but that sounds interesting. Did you make the repo public? I think you forgot to include a link.

Of course it belongs on the implementations list. Please send a PR to this repo with an update to `implementations.json`, and see the top of the README for some instructions.

You might also want to send this message to the [raft-dev list](https://groups.google.com/g/raft-dev) for visibility.

**Comment by EdoardoV97** [comment]
Hi @ongardie,

thank you for the feedback. Now the repo is public, here is the [link](https://github.com/EdoardoV97/Raft-Omnet).
Sure we will submit the PR and share the mex on the raft-dev list.

**Comment by ongardie** [comment]
Thanks for the PR to get this on the implementations list.

raft-dev post is here: https://groups.google.com/g/raft-dev/c/8EslP7lebgQ
though no public replies yet

Closing this issue now.
