### ISSUE TITLE
The raft.pdf file should have bookmarks to navigate easier

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [raft/raft.github.io#192]
I am NOT talking about the TOC in the content of the paper, but the metadata of the PDF.
When opening a book in PDF format, we should see something like below.

![image](https://github.com/raft/raft.github.io/assets/24372782/9a2f19aa-8c30-4202-babc-e0dbed61b0bf)

**Comment by ongardie** [comment]
I agree, but I'm not likely to get to this any time soon. You might prefer my [dissertation](https://github.com/ongardie/dissertation/) version, which does have a PDF outline.
