### ISSUE TITLE
Courses teaching Raft

### ISSUE THREAD

**Issue by deepmehtait** [raft/raft.github.io#40]
University Name: San Jose State University [https://msse.sjsu.edu/enterprise-software-technologies](url)
Course Name:CMPE 275 Enterprise Application Development [https://msse.sjsu.edu/enterprise-software-technologies](url) Spring 2015
Professor: John Gash [https://cmpe.sjsu.edu/profile/john-gash](url)
Details: Includes project to make Distributed file system using RAFT Algorithm for Fault tolerance, log replication and consistency
Project URL: [https://github.com/deepmehtait/Distributed-file-system-server-with-RAFT](url)

**Comment by ongardie** [comment]
Thank you, @deepmehtait. Hope you don't mind if this sits around for a week or two--I'm saving up some simple issues for a git beginner to work with.

**Comment by deepmehtait** [comment]
@ongardie sure, take your time.

**Comment by deepmehtait** [comment]
@ongardie Thank you very much.!

**Comment by ongardie** [comment]
@deepmehtait sorry for the wait. as you can tell, I finally timed out and closed all these myself :)
