### ISSUE TITLE
'eraft' project discontinued

### ISSUE THREAD

**Issue by chrisyunker** [raft/raft.github.io#55]
Should probably remove 'eraft' implementation from list:

https://github.com/djui/eraft

The project page says: "Please use ZRaft Lib; the implementation below is incomplete and discontinued."

**Comment by ongardie** [comment]
Fair enough @chrisyunker, if there's no value left in the eraft codebase. I'm on vacation at the moment, will get to this when I return. Or if you can send me a PR, I should be able to merge it.

**Comment by chrisyunker** [comment]
Apologies, I missed your reply.

I created a PR. Don't have strong opinions either way. I can't comment on the value of codebase. I didn't want to dive into it based on the author's comments, and would assume others would feel the same way.

**Comment by ongardie** [comment]
Thanks! Merged #56
