### ISSUE TITLE
Please, add .NET implementation into raft.github.io

### ISSUE THREAD

**Issue by hhblaze** [raft/raft.github.io#81]
[Raft.Net](https://github.com/hhblaze/Raft.Net)

**Comment by freddyrios** [comment]
@hhblaze was wondering why raft.net is not in the list.

perhaps filing a PR adding it to implementations.json would have more luck:
>Please contribute to the website by submitting pull requests (preferably) or creating issues. The most common way people contribute is by adding a new implementation to implementations.json. Note that the file is ordered lexicographically by GitHub repo URL, and this is strictly enforced by automated checks.
