### ISSUE TITLE
Randomization in Electing Leaders

### ISSUE THREAD

**Issue by nathanawmk** [raft/raft.github.io#82]
Since Raft uses randomized timers to elect leaders, how can one ensure that the randomization is sufficient random? 

How can one ensure that randomization in Raft is not based on pseudo random generator? (Flaw, Deliberate design -- backdoor) 

Thank you. 

Nathan Aw

**Comment by ongardie** [comment]
Hi Nathan,
Please ask your question on raft-dev: https://groups.google.com/forum/#!forum/raft-dev
Thanks,
Diego
