### ISSUE TITLE
Webpage not displaying changes in index.html

### ISSUE THREAD

**Issue by xingyif** [raft/raft.github.io#85]
I've added a new implementation of raft and updated index.html.
However, the website(raft.github.io) is still displaying the outdated one.
![screen shot 2018-07-02 at 10 25 22](https://user-images.githubusercontent.com/15064985/42176862-71c96a18-7df8-11e8-84ae-de47eb45d433.png)

**Comment by ongardie** [comment]
Hmm, it's updated for me. There's nothing that sits between index.html and GitHub Pages, but GitHub can take a little extra time to update some mirrors sometimes. Please let me know if this is still an issue in a few hours.

**Comment by ongardie** [comment]
Also note that the sort order on the website isn't supposed to be the same as in index.html, so you might find your implementation somewhere else in the table (and moving over time).

**Comment by xingyif** [comment]
Ah! It is updated. It was just not at the end of the table. I see it now. Thanks!
