### ISSUE TITLE
A fast Go Raft implementation capable of 10 million IO per second

### ISSUE THREAD

**Issue by lni** [raft/raft.github.io#95]
I just released a new multi-group Raft library in Go named Dragonboat. It is released under the Apache 2 license and available at https://github.com/lni/dragonboat

Could you please add this library to your raft implementation list? Thanks! 

It cover almost all features described in the Raft thesis - 
* leader election and log replication
* membership change
* log compaction and snapshotting
* ReadIndex based read-only queries
* Leadership transfer
* Non-voting members
* Node quiesce mode
* Client session feature described in the section 6.3 of the Raft PhD thesis. 

It is also the fastest open source Raft implementation on github.com, when tested with medium range hardware (3 x 22 cores Xeon servers running at 2.8GHz, each with NVME SSDs) -   
* 9 million proposals per second when using 48 Raft groups
* 10 million mixed read/write requests per second at 9:1 read-write ratio 

More details are available at https://github.com/lni/dragonboat

**Comment by ongardie** [comment]
This was added in #96, closing.
